export const LOGINSUCESS = 'LOGINSUCESS'
export const LOGINFAILED = 'LOGINFAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';